"""add cascade delete to all user and event foreign keys

Revision ID: 3e4f8b015ee5
Revises: d036e5040ca7
Create Date: 2026-04-22 22:23:12.743059

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3e4f8b015ee5"
down_revision: Union[str, Sequence[str], None] = "d036e5040ca7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("attendance_records_membername_fkey"),
        "attendance_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("attendance_records_event_id_fkey"),
        "attendance_records",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "attendance_records",
        "users",
        ["membername"],
        ["username"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "attendance_records", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("enrollments_event_id_fkey"), "enrollments", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("enrollments_membername_fkey"), "enrollments", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "enrollments", "users", ["membername"], ["username"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "enrollments", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("group_members_group_id_fkey"), "group_members", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("group_members_membername_fkey"), "group_members", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "group_members", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "group_members", "users", ["membername"], ["username"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("notification_prefs_username_fkey"),
        "notification_prefs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "notification_prefs",
        "users",
        ["username"],
        ["username"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("notifications_username_fkey"), "notifications", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "notifications", "users", ["username"], ["username"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("uploaded_media_uploaded_by_fkey"), "uploaded_media", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "uploaded_media",
        "users",
        ["uploaded_by"],
        ["username"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "uploaded_media", type_="foreignkey")
    op.create_foreign_key(
        op.f("uploaded_media_uploaded_by_fkey"),
        "uploaded_media",
        "users",
        ["uploaded_by"],
        ["username"],
    )
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.create_foreign_key(
        op.f("notifications_username_fkey"),
        "notifications",
        "users",
        ["username"],
        ["username"],
    )
    op.drop_constraint(None, "notification_prefs", type_="foreignkey")
    op.create_foreign_key(
        op.f("notification_prefs_username_fkey"),
        "notification_prefs",
        "users",
        ["username"],
        ["username"],
    )
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.drop_constraint(None, "group_members", type_="foreignkey")
    op.create_foreign_key(
        op.f("group_members_membername_fkey"),
        "group_members",
        "users",
        ["membername"],
        ["username"],
    )
    op.create_foreign_key(
        op.f("group_members_group_id_fkey"),
        "group_members",
        "groups",
        ["group_id"],
        ["id"],
    )
    op.drop_constraint(None, "enrollments", type_="foreignkey")
    op.drop_constraint(None, "enrollments", type_="foreignkey")
    op.create_foreign_key(
        op.f("enrollments_membername_fkey"),
        "enrollments",
        "users",
        ["membername"],
        ["username"],
    )
    op.create_foreign_key(
        op.f("enrollments_event_id_fkey"), "enrollments", "events", ["event_id"], ["id"]
    )
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.create_foreign_key(
        op.f("attendance_records_event_id_fkey"),
        "attendance_records",
        "events",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("attendance_records_membername_fkey"),
        "attendance_records",
        "users",
        ["membername"],
        ["username"],
    )
    # ### end Alembic commands ###
