"""rename_occurrence_id_to_event_id_occurrence_time_utc

Revision ID: 5bf61f71f29e
Revises: c7b2d8f680d6
Create Date: 2026-03-18 18:13:04.463807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5bf61f71f29e"
down_revision: Union[str, Sequence[str], None] = "c7b2d8f680d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records", sa.Column("event_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "attendance_records",
        sa.Column("occurrence_time_utc", sa.BigInteger(), nullable=False),
    )
    op.drop_constraint(
        op.f("attendance_records_occurrence_id_membername_key"),
        "attendance_records",
        type_="unique",
    )
    op.drop_index(op.f("idx_attendance_occurrence"), table_name="attendance_records")
    op.create_index(
        "idx_attendance_event_occurrence",
        "attendance_records",
        ["event_id", "occurrence_time_utc"],
        unique=False,
    )
    op.create_unique_constraint(
        None, "attendance_records", ["event_id", "occurrence_time_utc", "membername"]
    )
    op.create_foreign_key(None, "attendance_records", "events", ["event_id"], ["id"])
    op.drop_column("attendance_records", "occurrence_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records",
        sa.Column("occurrence_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.drop_constraint(None, "attendance_records", type_="unique")
    op.drop_index("idx_attendance_event_occurrence", table_name="attendance_records")
    op.create_index(
        op.f("idx_attendance_occurrence"),
        "attendance_records",
        ["occurrence_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("attendance_records_occurrence_id_membername_key"),
        "attendance_records",
        ["occurrence_id", "membername"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("attendance_records", "occurrence_time_utc")
    op.drop_column("attendance_records", "event_id")
    # ### end Alembic commands ###
