"""Initial schema

Revision ID: b85fba8c687a
Revises:
Create Date: 2026-03-18 02:36:24.264303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b85fba8c687a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("age_min", sa.Integer(), nullable=True),
        sa.Column("age_max", sa.Integer(), nullable=True),
        sa.Column("is_auto", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("nickname", sa.Text(), nullable=True),
        sa.Column("use_name_publicly", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("avatar_uri", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.BigInteger(), nullable=True),
        sa.Column("medical_info", sa.Text(), nullable=True),
        sa.Column("emergency_contact", sa.Text(), nullable=True),
        sa.Column("achievements", sa.Text(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_super_admin", sa.Integer(), nullable=False),
        sa.Column("roles", sa.Text(), nullable=False),
        sa.Column("last_login_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index("idx_users_status", "users", ["status"], unique=False)
    op.create_table(
        "venues",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("map_uri", sa.Text(), nullable=True),
        sa.Column("image_uri", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Integer(), nullable=False),
        sa.Column("is_featured", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attendance_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("occurrence_id", sa.BigInteger(), nullable=False),
        sa.Column("membername", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("previous_status", sa.Text(), nullable=True),
        sa.Column("leave_reason", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["membername"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("occurrence_id", "membername"),
    )
    op.create_index(
        "idx_attendance_occurrence",
        "attendance_records",
        ["occurrence_id"],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("actor_username", sa.String(length=50), nullable=True),
        sa.Column("target_username", sa.String(length=50), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=True),
        sa.Column("resource_id", sa.Text(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_actor", "audit_log", ["actor_username"], unique=False)
    op.create_index("idx_audit_target", "audit_log", ["target_username"], unique=False)
    op.create_index("idx_audit_timestamp", "audit_log", ["timestamp"], unique=False)
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("visibility", sa.Text(), nullable=False),
        sa.Column("venue_id", sa.Integer(), nullable=False),
        sa.Column("organizer_name", sa.Text(), nullable=True),
        sa.Column("coach_names", sa.Text(), nullable=True),
        sa.Column("rrule", sa.Text(), nullable=True),
        sa.Column("start_time", sa.BigInteger(), nullable=False),
        sa.Column("end_time", sa.BigInteger(), nullable=False),
        sa.Column("until_time", sa.BigInteger(), nullable=True),
        sa.Column("continued_as_event_id", sa.Integer(), nullable=True),
        sa.Column("continued_from_event_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_events_type", "events", ["type"], unique=False)
    op.create_index("idx_events_visibility", "events", ["visibility"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("membername", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["membername"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("group_id", "membername"),
    )
    op.create_table(
        "notification_prefs",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email_enabled", sa.Integer(), nullable=False),
        sa.Column("push_enabled", sa.Integer(), nullable=False),
        sa.Column("sms_enabled", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_read", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_notifications_user", "notifications", ["username"], unique=False
    )
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("membername", sa.String(length=50), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("is_trial", sa.Integer(), nullable=False),
        sa.Column("previous_status", sa.Text(), nullable=True),
        sa.Column("withdrawal_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("enrolled_at", sa.BigInteger(), nullable=True),
        sa.Column("withdrawn_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["membername"],
            ["users.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("membername", "event_id"),
    )
    op.create_index("idx_enrollments_event", "enrollments", ["event_id"], unique=False)
    op.create_index(
        "idx_enrollments_member", "enrollments", ["membername"], unique=False
    )
    op.create_table(
        "event_aux_info",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("stamp", sa.Text(), nullable=True),
        sa.Column("theme_color", sa.Integer(), nullable=True),
        sa.Column("image_uri", sa.Text(), nullable=True),
        sa.Column("is_featured", sa.Integer(), nullable=False),
        sa.Column("gallery_uris", sa.Text(), nullable=True),
        sa.Column("highlights", sa.Text(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("eligibility_note", sa.Text(), nullable=True),
        sa.Column("registration_deadline", sa.BigInteger(), nullable=True),
        sa.Column("urgency_text", sa.Text(), nullable=True),
        sa.Column("fees", sa.Integer(), nullable=True),
        sa.Column("currency", sa.Text(), nullable=True),
        sa.Column("includes", sa.Text(), nullable=True),
        sa.Column("timings", sa.Text(), nullable=True),
        sa.Column("age_range", sa.Text(), nullable=True),
        sa.Column("duration", sa.Text(), nullable=True),
        sa.Column("schedule", sa.Text(), nullable=True),
        sa.Column("full_description", sa.Text(), nullable=True),
        sa.Column("has_open_slots", sa.Integer(), nullable=False),
        sa.Column("batches", sa.Text(), nullable=True),
        sa.Column("facilities", sa.Text(), nullable=True),
        sa.Column("fee_structure", sa.Text(), nullable=True),
        sa.Column("package_offers", sa.Text(), nullable=True),
        sa.Column("club_membership", sa.Text(), nullable=True),
        sa.Column("offers", sa.Text(), nullable=True),
        sa.Column("contact_number", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "occurrence_overrides",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("occurrence_time", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("new_start_time", sa.BigInteger(), nullable=True),
        sa.Column("new_end_time", sa.BigInteger(), nullable=True),
        sa.Column("new_venue_id", sa.Integer(), nullable=True),
        sa.Column("new_organizer_name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("event_id", "occurrence_time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("occurrence_overrides")
    op.drop_table("event_aux_info")
    op.drop_index("idx_enrollments_member", table_name="enrollments")
    op.drop_index("idx_enrollments_event", table_name="enrollments")
    op.drop_table("enrollments")
    op.drop_index("idx_notifications_user", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("notification_prefs")
    op.drop_table("group_members")
    op.drop_index("idx_events_visibility", table_name="events")
    op.drop_index("idx_events_type", table_name="events")
    op.drop_table("events")
    op.drop_index("idx_audit_timestamp", table_name="audit_log")
    op.drop_index("idx_audit_target", table_name="audit_log")
    op.drop_index("idx_audit_actor", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_attendance_occurrence", table_name="attendance_records")
    op.drop_table("attendance_records")
    op.drop_table("venues")
    op.drop_index("idx_users_status", table_name="users")
    op.drop_table("users")
    op.drop_table("groups")
    # ### end Alembic commands ###
