"""add deleted_at to events and groups

Revision ID: d036e5040ca7
Revises: f5a3b7c9d2e4
Create Date: 2026-04-22 22:14:56.836723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d036e5040ca7"
down_revision: Union[str, Sequence[str], None] = "f5a3b7c9d2e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("deleted_at", sa.BigInteger(), nullable=True))
    op.add_column("groups", sa.Column("deleted_at", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "deleted_at")
    op.drop_column("events", "deleted_at")
    # ### end Alembic commands ###
